import { test } from 'node:test';
import assert from 'node:assert/strict';
import { FUNCTION_DEFINITION_SQL, reconcileFunctionDefinitions } from '../specs/210-personal-live-activation/deployment/pilot-function-definition-reconciliation.mjs';
function fixture(){
 const functions=Array.from({length:64},(_,i)=>({key:['public','f'+i,'[]'],raw:'a'.repeat(64),lf:(i<62?'b':'a').repeat(64),bytes:100,pairs:i<62?3:0}));
 return {approved:new Set(functions.slice(0,26).map(x=>JSON.stringify(x.key))),capture:{database:'endvera_function_definition_review_20260910',version:'170011',readOnly:'on',historyCount:70,functions},local:{objects:functions.map(x=>({family:'function',key:x.key,properties:{definitionHash:x.raw}}))},remote:{objects:functions.map((x,i)=>({family:'function',key:x.key,properties:{definitionHash:i<26?x.lf:x.raw}}))}};
}
test('36 raw-only,2 raw-and-LF,26 history-selectedLF, no authority',()=>{const f=fixture(),r=reconcileFunctionDefinitions(f.capture,f.local,f.remote,f.approved);assert.equal(r.nativeBaselineMatches,64);assert.equal(r.rawRemoteMatches,38);assert.equal(r.lfRemoteMatches,28);assert.equal(r.explainedDeltas,26);assert.equal(r.selectedRepresentationMatches,64);assert.equal(r.unmatched.length,0);assert.equal(r.backupVerified,false);assert.equal(r.fullSchemaEquivalent,false);});
test('LF hash alone without exact historical corroboration never passes',()=>{const f=fixture(),r=reconcileFunctionDefinitions(f.capture,f.local,f.remote);assert.equal(r.selectedRepresentationMatches,38);assert.equal(r.explainedDeltas,0);assert.equal(r.unmatched.length,26);});
test('missing or duplicate exact signature refuses',()=>{for(const mutation of [f=>f.capture.functions.pop(),f=>f.capture.functions[1].key=f.capture.functions[0].key]){const f=fixture();mutation(f);assert.throws(()=>reconcileFunctionDefinitions(f.capture,f.local,f.remote));}});
test('unknown native mutation is retained, not normalized away',()=>{const f=fixture();f.capture.functions[0].raw='c'.repeat(64);const r=reconcileFunctionDefinitions(f.capture,f.local,f.remote,f.approved);assert.equal(r.nativeBaselineMatches,63);assert.equal(r.unmatched.length,1);});
test('unexplained remote full-definition delta remains failed',()=>{const f=fixture();f.remote.objects[0].properties.definitionHash='d'.repeat(64);const r=reconcileFunctionDefinitions(f.capture,f.local,f.remote,f.approved);assert.equal(r.lfRemoteMatches,27);assert.equal(r.unmatched.length,1);});
test('wrong native DB, version, history and write session refuse',()=>{for(const [k,v]of [['database','postgres'],['version','180006'],['historyCount',79],['readOnly','off']]){const f=fixture();f.capture[k]=v;assert.throws(()=>reconcileFunctionDefinitions(f.capture,f.local,f.remote));}});
test('SQL hashes whole deparser output with only CRLF replacement',()=>{assert.match(FUNCTION_DEFINITION_SQL,/pg_get_functiondef\(p.oid\) AS definition/);assert.match(FUNCTION_DEFINITION_SQL,/replace\(definition,chr\(13\)\|\|chr\(10\),chr\(10\)\)/);assert.match(FUNCTION_DEFINITION_SQL,/BEGIN READ ONLY/);assert.doesNotMatch(FUNCTION_DEFINITION_SQL,/trim\(|regexp_replace|CREATE|ALTER|DROP/i);});
