import { createHash } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { buildPilotDataPreservationQuery, compareSuppliedPilotDataPreservation } from "../specs/210-personal-live-activation/deployment/pilot-data-preservation.mjs";
import { buildPilotMigrationCatalog } from "../specs/210-personal-live-activation/deployment/pilot-migration-catalog.mjs";
import { compareSuppliedPilotSchemaSnapshots } from "../specs/210-personal-live-activation/deployment/pilot-schema-drift.mjs";

type Entry = { family: string; key: string[]; properties: Record<string, unknown> };
const digest = (s: string) => createHash("sha256").update(s).digest("hex");
const families = ["table","column","constraint","index","function","trigger","enum","acl","policy","extension","unsupported"];
const migrationCatalog = buildPilotMigrationCatalog();
function source(tableName = "items") {
  const acl = (kind: string, name: string, field = ""): Entry => ({ family: "acl", key: ["public",kind,name,field], properties: { owner: "review_synthetic", aclHash: null } });
  const objects: Entry[] = [acl("SCHEMA","public")];
  for (const [name, fields] of [[tableName,["id","payload"]],["_prisma_migrations",["id","checksum","finished_at","migration_name","logs","rolled_back_at","started_at","applied_steps_count"]]] as const) {
    objects.push({ family: "table", key: ["public",name], properties: { persistence: "p", accessMethod: "heap", replicaIdentity: "d", rls: false, forceRls: false, optionsHash: null, tablespace: null } },acl("TABLE",name));
    fields.forEach((field, i) => objects.push({ family: "column", key: ["public",name,field], properties: { position: i+1, type: ["pg_catalog",field === "applied_steps_count" ? "int4" : ["started_at","finished_at","rolled_back_at"].includes(field) ? "timestamp" : "text"], modifier: -1, dimensions: 0, notNull: false, notNullCount: null, notNullEnforced: null, notNullValidated: null, generated: "", identity: "", defaultHash: null, collation: null, collationHash: null, storage: "x", compression: "", optionsHash: null } },acl("COLUMN",name,field)));
  }
  const catalog70 = { version: "personal-pilot-schema-snapshot-v1", server: { versionNum: 170011, versionHash: digest("server"), encoding: "UTF8", collation: "C", ctype: "C", localeProvider: "c", collationVersion: null, localeHash: null, searchPathHash: digest("path"), searchPathSafe: true }, objectCount: objects.length, familyCounts: Object.fromEntries(families.map(f => [f,objects.filter(x=>x.family===f).length])), objects, truncated: false };
  return { catalog70, migrationCatalog, expectedCatalogSha256: compareSuppliedPilotSchemaSnapshots(catalog70,catalog70).leftSha256 };
}
function rebind(s: ReturnType<typeof source>) {
  s.catalog70.objectCount=s.catalog70.objects.length;
  s.catalog70.familyCounts=Object.fromEntries(families.map(f=>[f,s.catalog70.objects.filter(x=>x.family===f).length]));
  s.expectedCatalogSha256=compareSuppliedPilotSchemaSnapshots(s.catalog70,s.catalog70).leftSha256;
  return s;
}
function fixture() {
  const s=source(), plan=buildPilotDataPreservationQuery(s);
  const capture={version:plan.version,planSha256:plan.planSha256,catalogSha256:plan.manifest.suppliedCatalogSha256,tables:plan.manifest.tables.map((t:{name:string})=>({table:t.name,rowCount:t.name==="_prisma_migrations"?"70":"3",digest:digest(t.name),truncated:false,historyComplete:true}))};
  return {s,plan,left:structuredClone(capture),right:structuredClone(capture)};
}
describe("peer aggregate-only preservation boundary",()=>{
  it("positive control is frozen, scoped, and never permission",()=>{const f=fixture(),r=compareSuppliedPilotDataPreservation(f.s,f.left,f.right);expect(r.status).toBe("SUPPLIED_OLD_COLUMN_AGGREGATES_MATCH");expect(r).toMatchObject({changedTables:0,executionAuthorized:false,backupVerified:false,snapshotProvenanceVerified:false,newColumnsVerified:false,newProofTablesVerified:false,databaseRead:false});expect(Object.isFrozen(r)).toBe(true);expect(Object.isFrozen(f.plan.manifest.tables[0].columns)).toBe(true);expect(JSON.stringify(r)).not.toContain(f.left.tables[0].digest);});
  it("same row count but changed digest is not preserved",()=>{const f=fixture();f.right.tables[1].digest=digest("changed-row");expect(compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toMatchObject({status:"SUPPLIED_OLD_COLUMN_AGGREGATES_DIFFER",changedCounts:0,changedDigests:1,changedTables:1});});
  it("count difference independently fails even supplied digest equal",()=>{const f=fixture();f.right.tables[1].rowCount="4";expect(compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toMatchObject({changedCounts:1,changedDigests:0,changedTables:1});});
  it("result ordering does not change multiset table matching",()=>{const f=fixture();f.right.tables.reverse();expect(compareSuppliedPilotDataPreservation(f.s,f.left,f.right).changedTables).toBe(0);});
  it.each(["0","01","-1","+1","1e2"," 3","3.0","9007199254740993","9223372036854775808","500001"])("malformed/overflow/nonempty-zero count %s refuses",count=>{const f=fixture();f.right.tables[1].rowCount=count;expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();});
  it("actual empty aggregate uses SHA256 empty bytes",()=>{const f=fixture();for(const c of [f.left,f.right])Object.assign(c.tables[1],{rowCount:"0",digest:digest("")});expect(compareSuppliedPilotDataPreservation(f.s,f.left,f.right).changedTables).toBe(0);});
  it.each(["missing","extra","duplicate","unknown"])("%s table result refuses",mode=>{const f=fixture();if(mode==="missing")f.right.tables.pop();if(mode==="extra")f.right.tables.push(structuredClone(f.right.tables[0]));if(mode==="duplicate")f.right.tables[1]=structuredClone(f.right.tables[0]);if(mode==="unknown")f.right.tables[1].table="foreign";expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();});
  it.each(["planSha256","catalogSha256","version"])("wrong %s refuses",field=>{const f=fixture();Object.assign(f.right,{[field]:digest("different")});expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();});
  it.each(["truncated","historyComplete"])("false safety sentinel %s refuses",field=>{const f=fixture();Object.assign(f.right.tables[1],{[field]:field==="truncated"});expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();});
  it("prefix70 capture cannot pass with79 history rows",()=>{const f=fixture();f.right.tables[0].rowCount="79";expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow(/HISTORY/);});
  it("accessors never run in source or captures",()=>{for(const inSource of [true,false]){const f=fixture(),spy=vi.fn();Object.defineProperty(inSource?f.s:f.right,"planSha256",{get:spy,enumerable:true});expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();expect(spy).not.toHaveBeenCalled();}});
  it("prototype key, sparse array and extra row keys refuse",()=>{for(const mode of ["proto","sparse","extra"]){const f=fixture();if(mode==="proto")Object.defineProperty(f.right,"__proto__",{value:{},enumerable:true});if(mode==="sparse")delete f.right.tables[1];if(mode==="extra")Object.assign(f.right.tables[0],{sql:"SELECT secret"});expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();}});
  it("input array cap is checked without visiting indexed accessor",()=>{const f=fixture(),spy=vi.fn();const huge=new Array(25001);Object.defineProperty(huge,"0",{get:spy,enumerable:true});Object.assign(f.right,{tables:huge});expect(()=>compareSuppliedPilotDataPreservation(f.s,f.left,f.right)).toThrow();expect(spy).not.toHaveBeenCalled();});
  it("duplicate position is not a supported old-column plan",()=>{const s=source(),cols=s.catalog70.objects.filter(x=>x.family==="column"&&x.key[1]==="items");cols[1].properties.position=1;rebind(s);expect(()=>buildPilotDataPreservationQuery(s)).toThrow(/UNSUPPORTED_COLUMN/);});
  it("caller column permutation has same source-bound SQL",()=>{const s=source(),a=buildPilotDataPreservationQuery(s);s.catalog70.objects.reverse();const b=buildPilotDataPreservationQuery(s);expect(b.sql).toBe(a.sql);});
  it("changed old column identity changes plan binding",()=>{const s=source(),a=buildPilotDataPreservationQuery(s);for(const e of s.catalog70.objects){if(e.family==="column"&&e.key[1]==="items"&&e.key[2]==="payload")e.key[2]="new_payload";if(e.family==="acl"&&e.key[1]==="COLUMN"&&e.key[2]==="items"&&e.key[3]==="payload")e.key[3]="new_payload";}const b=buildPilotDataPreservationQuery(rebind(s));expect(b.planSha256).not.toBe(a.planSha256);});
  it("quoted identifiers and literal aliases keep supplied punctuation data",()=>{const name=`items'";--`,s=source(name),p=buildPilotDataPreservationQuery(s);expect(p.sql).toContain(`FROM ONLY "public"."items'"";--" AS t`);expect(p.sql).toContain(`SELECT 'items''";--'::pg_catalog.text AS "table"`);});
  it("oversized UTF8 identifier refuses despite short UTF16 count",()=>{expect(()=>buildPilotDataPreservationQuery(source("é".repeat(32)))).toThrow(/IDENTIFIER/);});
  it("array lower bounds are retained, not just to_jsonb(array)",()=>{const s=source(),c=s.catalog70.objects.find(x=>x.family==="column"&&x.key[1]==="items"&&x.key[2]==="payload")!;Object.assign(c.properties,{type:["pg_catalog","_text"],dimensions:1});const p=buildPilotDataPreservationQuery(rebind(s));expect(p.sql).toContain(`'dimensions',pg_catalog.array_dims(t."payload"),'value',pg_catalog.to_jsonb(t."payload")`);});
  it("SQL is one fixed read-only repeatable snapshot with exact serializers",()=>{const {plan}=fixture();for(const part of ["BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY","statement_timeout='30000'","lock_timeout='2000'","transaction_timeout='45000'","TimeZone='UTC'","DateStyle='ISO, YMD'","IntervalStyle='postgres'","bytea_output='hex'","extra_float_digits=3","row_security=off","search_path=pg_catalog"]){expect(plan.sql).toContain(part);}expect(plan.sql.match(/BEGIN TRANSACTION/g)).toHaveLength(1);expect(plan.sql.match(/COMMIT;/g)).toHaveLength(1);expect(plan.sql).not.toMatch(/\b(?:CREATE|UPDATE|DELETE|INSERT|COPY|CALL|DO)\b/);});
  it("old history filter is exactly70 names, not all79 nor arbitrarywhere",()=>{const {plan}=fixture();expect(plan.manifest.historicalMigrationNames).toHaveLength(70);expect(plan.sql).toContain(`WHERE t."migration_name" IN (`);expect(plan.sql).toContain(migrationCatalog.entries[69].migrationName);expect(plan.sql).not.toContain(migrationCatalog.entries[70].migrationName);expect(plan.sql).toContain('count(DISTINCT old_row."migration_name")=70');});
  it("data digest uses ordered multiset without DISTINCT and caps overflow",()=>{const {plan}=fixture();expect(plan.sql).toContain("string_agg(");expect(plan.sql).toContain('COLLATE "C"');expect(plan.sql).not.toMatch(/string_agg\(DISTINCT/);expect(plan.sql).toContain("LIMIT 500001");expect(plan.sql).toContain('count(*)::pg_catalog.text AS "rowCount"');const a=digest("row-A"),b=digest("row-B");const multiset=(r:string[])=>digest([...r].sort().join(""));expect(multiset([a,a,b])).not.toBe(multiset([a,b,b]));expect(multiset([a,a,b])).toBe(multiset([b,a,a]));});
});
