import { requireRole } from "@/lib/authz";
import { boundOutboundActionSchema } from "@/lib/construction-assistant-v1/outbound";
import { inboxForUser } from "@/server/construction-assistant-v1/queries";
import { approveLocalOutboundSimulation } from "@/server/actions/construction-assistant-v1";
import { LocalConstructionSimulator } from "@/components/construction-assistant-v1/local-simulator";
import { Card, CardBody, EmptyState, PageTitle, SectionLabel } from "@/components/ui";

export default async function ConstructionInboxPage() {
  const user = await requireRole("CLIENT");
  const inbox = await inboxForUser(user.id);
  return <div className="space-y-6 text-[#F7F6F3]"><PageTitle tone="night" title="Boîte de réception" sub="Conversation, décisions et actions préparées — sans transport réel." />{!inbox ? <EmptyState tone="night" title="Aucun espace" body="Initialisez d’abord le dossier Construction." /> : <><LocalConstructionSimulator workspaceId={inbox.workspace.id} />
    <section><SectionLabel tone="night" className="mb-3">Actions à approuver</SectionLabel><div className="space-y-3">{inbox.actions.length === 0 ? <p className="text-sm text-[#8A9099]">Aucune action préparée.</p> : inbox.actions.map((action) => { const parsed = boundOutboundActionSchema.safeParse(action.payload); return <Card key={action.id} tone="night"><CardBody><p className="font-medium">Message à {action.contact?.displayName ?? "contact"}</p>{parsed.success ? <><p className="mt-2 rounded-md bg-black/20 p-3 text-sm text-[#B7BDC7]">{parsed.data.body}</p><p className="mt-2 text-xs text-[#8A9099]">{parsed.data.channel} · {parsed.data.normalizedRecipient} · version {action.version}</p></> : <p className="mt-2 text-sm text-[#FF9A8B]">Payload fermé invalide.</p>}<div className="mt-3 flex items-center justify-between"><p className="font-mono text-[11px] uppercase text-[#C9A76A]">{action.status}</p>{parsed.success && action.status === "proposed" ? <form action={approveLocalOutboundSimulation}><input type="hidden" name="workspaceId" value={inbox.workspace.id}/><input type="hidden" name="actionId" value={action.id}/><input type="hidden" name="expectedVersion" value={action.version}/><input type="hidden" name="expectedPayloadHash" value={action.payloadHash}/><button className="rounded-md bg-[#D87526] px-3 py-2 text-sm font-semibold text-white">Approuver et livrer localement</button></form> : null}</div></CardBody></Card>; })}</div></section>
    <section><SectionLabel tone="night" className="mb-3">Historique des communications</SectionLabel><Card tone="night"><div className="divide-y divide-white/10">{inbox.messages.map((message) => <div key={message.id} className="p-4"><div className="flex justify-between gap-3"><p className="font-medium">{message.direction === "inbound" ? "Reçu" : "Sortant simulé"} · {message.channel}</p><p className="font-mono text-[11px] uppercase text-[#8A9099]">{message.status}</p></div><p className="mt-2 text-sm text-[#B7BDC7]">{message.originalBody}</p><p className="mt-2 text-xs text-[#6F7680]">{message.providerMessageId ?? "Portail"} · {message.createdAt.toISOString()}</p></div>)}</div></Card></section></>}</div>;
}
