import {z} from "zod";
import type {MobileWorkspace} from "@/lib/contracts";
export const EMAIL_POLICY_VERSION="r26-local-disabled-v1" as const;const id=z.string().min(1).max(200);const ref=z.string().regex(/^email_[a-f0-9]{64}$/u);const provider=z.enum(["GOOGLE_GMAIL","MICROSOFT_GRAPH"]);
export const mobileEmailAccountCommandSchema=z.discriminatedUnion("action",[z.object({schemaVersion:z.literal(1),action:z.literal("PREPARE_EMAIL_ACCOUNT"),commandId:z.string().uuid(),workspaceId:id,provider,accountRef:ref,mailboxScopeRef:ref,capabilities:z.array(z.enum(["READ_METADATA","READ_SELECTED_CONTENT","PREPARE_DRAFT"])).min(1)}).strict(),z.object({schemaVersion:z.literal(1),action:z.literal("REVOKE_EMAIL_ACCOUNT"),commandId:z.string().uuid(),workspaceId:id,accountId:id,expectedVersion:z.number().int().positive()}).strict()]);
export const mobileEmailDraftCommandSchema=z.discriminatedUnion("action",[z.object({schemaVersion:z.literal(1),action:z.literal("PREPARE_EMAIL_DRAFT"),commandId:z.string().uuid(),workspaceId:id,accountId:id,projectId:id,contactId:id,toRef:ref,ccRefs:z.array(ref),subject:z.string().min(1).max(998),body:z.string().min(1).max(10_000),threadRef:ref.nullable(),selectedEvidenceIds:z.array(id),expectedPolicyVersion:z.literal(EMAIL_POLICY_VERSION)}).strict(),z.object({schemaVersion:z.literal(1),action:z.literal("APPROVE_EMAIL_DRAFT"),commandId:z.string().uuid(),workspaceId:id,draftId:id,expectedVersion:z.number().int().positive(),expectedPayloadHash:z.string().regex(/^[a-f0-9]{64}$/u)}).strict()]);
const cockpit=z.object({schemaVersion:z.literal(1),workspaceId:id,role:z.enum(["owner","admin","field_worker"]),accounts:z.array(z.object({id,provider,status:z.string(),version:z.number().int(),capabilities:z.array(z.string()),credentialStored:z.literal(false),externalTransportEnabled:z.literal(false)}).strict()),contacts:z.array(z.object({id,projectId:id.nullable(),displayName:z.string(),emailRef:ref}).strict()),events:z.array(z.object({id,projectId:id.nullable(),contactId:id.nullable(),subject:z.string().nullable(),body:z.string().nullable(),status:z.string(),evidenceLinkCount:z.number().int(),occurredAt:z.string().datetime()}).strict()),drafts:z.array(z.object({id,projectId:id,contactId:id,toRef:ref.nullable(),subject:z.string().nullable(),body:z.string().nullable(),version:z.number().int(),payloadHash:z.string().nullable(),status:z.string(),createdAt:z.string().datetime()}).strict()),counts:z.object({accounts:z.number().int(),events:z.number().int(),preparedUnsent:z.number().int()}).strict(),providerObserved:z.literal(false),externalTransportEnabled:z.literal(false)}).strict();
const forbidden=new Set(["subject","body","toRef","payloadHash","providerMessageRef","threadRef","evidenceId","amount"]);function leaks(v:unknown):boolean{if(Array.isArray(v))return v.some(leaks);if(!v||typeof v!=="object")return false;return Object.entries(v).some(([k,n])=>forbidden.has(k)||leaks(n));}
export function parseMobileEmailCockpit(v:unknown){if(v&&typeof v==="object"&&(v as {role?:unknown}).role==="field_worker"&&leaks(v))throw new Error("MOBILE_EMAIL_FIELD_LEAK_REFUSED");return cockpit.parse(v);}
export type MobileEmailCockpit=ReturnType<typeof parseMobileEmailCockpit>;export type MobileEmailCommand=z.infer<typeof mobileEmailAccountCommandSchema>|z.infer<typeof mobileEmailDraftCommandSchema>;
function manager(w:MobileWorkspace){if(w.role!=="OWNER"&&w.role!=="OFFICE_MANAGER")throw new Error("MOBILE_EMAIL_MANAGEMENT_REFUSED");}
export function createPrepareEmailAccountCommand(input:{workspace:MobileWorkspace;commandId:string;provider:"GOOGLE_GMAIL"|"MICROSOFT_GRAPH";accountRef:string;mailboxScopeRef:string}){manager(input.workspace);return mobileEmailAccountCommandSchema.parse({schemaVersion:1,action:"PREPARE_EMAIL_ACCOUNT",commandId:input.commandId,workspaceId:input.workspace.id,provider:input.provider,accountRef:input.accountRef,mailboxScopeRef:input.mailboxScopeRef,capabilities:["READ_METADATA","READ_SELECTED_CONTENT","PREPARE_DRAFT"]});}
export function createPrepareEmailDraftCommand(input:{workspace:MobileWorkspace;commandId:string;accountId:string;projectId:string;contactId:string;toRef:string;subject:string;body:string}){manager(input.workspace);return mobileEmailDraftCommandSchema.parse({schemaVersion:1,action:"PREPARE_EMAIL_DRAFT",commandId:input.commandId,workspaceId:input.workspace.id,accountId:input.accountId,projectId:input.projectId,contactId:input.contactId,toRef:input.toRef,ccRefs:[],subject:input.subject,body:input.body,threadRef:null,selectedEvidenceIds:[],expectedPolicyVersion:EMAIL_POLICY_VERSION});}
