-- Protections Prisma's schema language cannot express. Uses only built-in
-- PostgreSQL functions so the same migration runs on managed Postgres and the
-- local PGlite development server.

-- Only one unresolved client-quality dispute may exist for a task.
CREATE UNIQUE INDEX "Dispute_one_pending_per_task"
  ON "Dispute" ("taskId")
  WHERE "outcome" = 'pending';

-- Clean file rows must carry the evidence generated by the scanning pipeline.
ALTER TABLE "File"
  ADD CONSTRAINT "File_clean_requires_scan_evidence"
  CHECK (
    "scanStatus" <> 'clean'
    OR (
      "sha256" IS NOT NULL
      AND "detectedMime" IS NOT NULL
      AND "scannedAt" IS NOT NULL
    )
  );

CREATE OR REPLACE FUNCTION second_shift_protect_task_invariants()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD."firstCompletedAt" IS NOT NULL
     AND NEW."firstCompletedAt" IS DISTINCT FROM OLD."firstCompletedAt" THEN
    RAISE EXCEPTION 'firstCompletedAt is immutable once set';
  END IF;

  IF OLD."status" NOT IN ('submitted', 'pricing_review')
     AND NEW."isInternal" IS DISTINCT FROM OLD."isInternal" THEN
    RAISE EXCEPTION 'isInternal is frozen after pricing';
  END IF;

  IF NEW."status" = 'open'
     AND OLD."status" = 'awaiting_payment'
     AND NOT NEW."isInternal"
     AND NOT EXISTS (
       SELECT 1
       FROM "Payment" p
       WHERE p."taskId" = NEW."id" AND p."status" = 'received'
     ) THEN
    RAISE EXCEPTION 'a paid client task cannot enter the pool without received payment';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "Task_protect_invariants"
BEFORE UPDATE ON "Task"
FOR EACH ROW EXECUTE FUNCTION second_shift_protect_task_invariants();

-- A completed task and its worker payout must commit together.
CREATE OR REPLACE FUNCTION second_shift_completed_task_has_payout()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."status" = 'completed'
     AND NEW."claimedById" IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM "Payout" p
       WHERE p."taskId" = NEW."id" AND p."vaId" = NEW."claimedById"
     ) THEN
    RAISE EXCEPTION 'completed task has no worker payout';
  END IF;
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "Task_completed_requires_payout"
AFTER INSERT OR UPDATE OF "status" ON "Task"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION second_shift_completed_task_has_payout();

-- Ledger sequencing and hashes are assigned inside Postgres under a
-- transaction-scoped advisory lock, so concurrent webhooks form one chain.
CREATE OR REPLACE FUNCTION second_shift_ledger_assign()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  previous_seq bigint;
  previous_hash text;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('second-shift-ledger'));
  SELECT "seq", "rowHash"
    INTO previous_seq, previous_hash
    FROM "LedgerEntry"
    ORDER BY "seq" DESC
    LIMIT 1;

  NEW."seq" := COALESCE(previous_seq, 0) + 1;
  NEW."occurredAt" := clock_timestamp();
  NEW."prevHash" := COALESCE(previous_hash, repeat('0', 64));
  NEW."rowHash" :=
    md5(
      concat_ws(
        '|',
        NEW."seq"::text,
        NEW."kind"::text,
        NEW."amountCents"::text,
        NEW."currency",
        COALESCE(NEW."categorySlug", ''),
        NEW."sourceKind",
        NEW."sourceId",
        NEW."occurredAt"::text,
        NEW."isInternal"::text,
        NEW."publiclyVisible"::text,
        NEW."prevHash"
      )
    )
    ||
    md5(
      'second-shift-ledger-v1|' ||
      concat_ws(
        '|',
        NEW."seq"::text,
        NEW."kind"::text,
        NEW."amountCents"::text,
        NEW."currency",
        COALESCE(NEW."categorySlug", ''),
        NEW."sourceKind",
        NEW."sourceId",
        NEW."occurredAt"::text,
        NEW."isInternal"::text,
        NEW."publiclyVisible"::text,
        NEW."prevHash"
      )
    );
  RETURN NEW;
END;
$$;

CREATE TRIGGER "LedgerEntry_assign_chain"
BEFORE INSERT ON "LedgerEntry"
FOR EACH ROW EXECUTE FUNCTION second_shift_ledger_assign();

CREATE OR REPLACE FUNCTION second_shift_ledger_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'LedgerEntry is append-only';
END;
$$;

CREATE TRIGGER "LedgerEntry_no_update_or_delete"
BEFORE UPDATE OR DELETE ON "LedgerEntry"
FOR EACH ROW EXECUTE FUNCTION second_shift_ledger_immutable();

CREATE TRIGGER "LedgerEntry_no_truncate"
BEFORE TRUNCATE ON "LedgerEntry"
FOR EACH STATEMENT EXECUTE FUNCTION second_shift_ledger_immutable();
