import type { DevBenchCatalog } from "@/lib/engineering-factory/devbench";

/**
 * V1 is deliberately a test catalog, not a prompt corpus. A participant gets
 * the scoped ticket and repository checkout through an approved harness; this
 * file records only the locally verifiable result expected from that run.
 */
export const DEV_BENCH_V1: DevBenchCatalog = {
  version: 1,
  name: "ENDVERA Engineering Factory DevBench v1",
  cases: [
    {
      id: "EF-001",
      title: "Deterministic workflow compiler",
      family: "deterministic-core",
      objective: "Preserve deterministic compilation and fail-closed mandate gates.",
      sourcePaths: ["src/lib/ai-work-engine/compile.ts", "test/workflow-compile.test.ts"],
      commands: ["npm run test:run -- test/workflow-compile.test.ts"],
      oracle: ["same input produces same compiled plan", "sensitive or access-gated mandates refuse automation"],
      requiredEvidence: ["targeted test output", "named mutation restored byte-exactly"],
      mutation: "compile-gate-bypass",
      providerExposure: "none",
      forbiddenPaths: ["src/lib/db.ts", "prisma/schema.prisma"],
    },
    {
      id: "EF-002",
      title: "Generated capability contract",
      family: "contract-drift",
      objective: "Keep the planner contract derived from the same runtime constraints it describes.",
      sourcePaths: ["src/lib/ai-work-engine/capability-contract.ts", "test/capability-contract.test.ts"],
      commands: ["npm run test:run -- test/capability-contract.test.ts"],
      oracle: ["runtime descriptors and published contract remain identical", "unsupported parameters remain rejected"],
      requiredEvidence: ["targeted test output", "contract-drift mutation"],
      mutation: "capability-contract-drift",
      providerExposure: "none",
      forbiddenPaths: ["prisma/schema.prisma"],
    },
    {
      id: "EF-003",
      title: "Outbound URL safety",
      family: "network-safety",
      objective: "Reject unsafe schemes, credentials, ports and internal addresses before an outbound fetch.",
      sourcePaths: ["src/lib/net/url-safety.ts", "test/url-safety.test.ts"],
      commands: ["npm run test:run -- test/url-safety.test.ts"],
      oracle: ["only approved http and https targets pass", "private and credential-bearing URLs fail closed"],
      requiredEvidence: ["targeted test output", "ssrf-allow mutation"],
      mutation: "ssrf-allow-private-address",
      providerExposure: "none",
      forbiddenPaths: ["src/app"],
    },
    {
      id: "EF-004",
      title: "Client and server bundle boundary",
      family: "client-server-boundary",
      objective: "Keep server-only values out of client components before a production build finds the error.",
      sourcePaths: ["test/client-server-boundary.test.ts", "src/lib/ai-work-engine/primitive-vocabulary.ts"],
      commands: ["npm run test:run -- test/client-server-boundary.test.ts"],
      oracle: ["client files cannot import values from server-only modules", "type-only imports remain permitted"],
      requiredEvidence: ["targeted test output", "server-import mutation"],
      mutation: "client-imports-server-value",
      providerExposure: "none",
      forbiddenPaths: ["prisma/schema.prisma"],
    },
    {
      id: "EF-005",
      title: "Replay fixture provenance",
      family: "provider-replay",
      objective: "Reject unverifiable replay evidence and keep request fingerprints stable.",
      sourcePaths: ["test/support/provider-replay.ts", "test/golden-fixture.test.ts"],
      commands: ["npm run test:run -- test/golden-fixture.test.ts"],
      oracle: ["fixture identity follows canonical request bytes", "incomplete paid recordings remain incomplete"],
      requiredEvidence: ["targeted test output", "fixture-provenance mutation"],
      mutation: "fixture-hash-ignored",
      providerExposure: "none",
      forbiddenPaths: ["test/golden"],
    },
    {
      id: "EF-006",
      title: "Synthetic provider execution",
      family: "synthetic-execution",
      objective: "Exercise real provider response shapes without a network request or spend.",
      sourcePaths: ["test/synthetic-provider.test.ts", "test/support/synthetic-responder.ts", "test/support/provider-replay.ts"],
      commands: ["npm run test:run -- test/synthetic-provider.test.ts"],
      oracle: ["synthetic mode reports zero spend", "unroutable requests fail rather than invent a response"],
      requiredEvidence: ["targeted test output", "synthetic-fallback mutation"],
      mutation: "synthetic-response-invention",
      providerExposure: "none",
      forbiddenPaths: [".env", "src/lib/settings.ts"],
    },
    {
      id: "EF-007",
      title: "Account spend circuit breaker",
      family: "spend-safety",
      objective: "Reserve account exposure before provider dispatch and never leak operational ceilings.",
      sourcePaths: ["src/server/account-spend.ts", "test/account-spend-ceiling.test.ts"],
      commands: ["npm run test:run -- test/account-spend-ceiling.test.ts"],
      oracle: ["reservation precedes dispatch", "refusal cannot dispatch or reveal spend configuration"],
      requiredEvidence: ["targeted test output", "breaker-order mutation"],
      mutation: "provider-dispatch-before-reservation",
      providerExposure: "none",
      forbiddenPaths: ["prisma/migrations"],
    },
    {
      id: "EF-008",
      title: "File ingestion safety",
      family: "file-security",
      objective: "Keep hostile or ambiguous uploaded files outside executable and unsafe paths.",
      sourcePaths: ["test/file-security.test.ts", "src/lib/ai-work-engine/primitives/files.ts"],
      commands: ["npm run test:run -- test/file-security.test.ts"],
      oracle: ["unsafe file conditions are rejected before processing", "accepted file handling remains bounded"],
      requiredEvidence: ["targeted test output", "file-admission mutation"],
      mutation: "file-admission-bypass",
      providerExposure: "none",
      forbiddenPaths: ["prisma/schema.prisma", "src/app"],
    },
  ],
};
