import { z } from "zod";

export const EMAIL_SCHEMA_VERSION = 1 as const;
export const EMAIL_POLICY_VERSION = "r26-local-disabled-v1" as const;
export const emailProviderSchema = z.enum(["GOOGLE_GMAIL", "MICROSOFT_GRAPH"]);
export const emailRefSchema = z.string().regex(/^email_[a-f0-9]{64}$/u);
export const emailCapabilitiesSchema = z.array(z.enum(["READ_METADATA", "READ_SELECTED_CONTENT", "PREPARE_DRAFT"]))
  .min(1).refine((v) => new Set(v).size === v.length, "duplicate capability");

export const prepareEmailAccountCommandSchema = z.object({schemaVersion:z.literal(1),action:z.literal("PREPARE_EMAIL_ACCOUNT"),commandId:z.string().uuid(),workspaceId:z.string().min(1).max(160),provider:emailProviderSchema,accountRef:emailRefSchema,mailboxScopeRef:emailRefSchema,capabilities:emailCapabilitiesSchema}).strict();
export const revokeEmailAccountCommandSchema = z.object({schemaVersion:z.literal(1),action:z.literal("REVOKE_EMAIL_ACCOUNT"),commandId:z.string().uuid(),workspaceId:z.string().min(1).max(160),accountId:z.string().min(1).max(160),expectedVersion:z.number().int().positive()}).strict();
export const emailAccountCommandSchema = z.discriminatedUnion("action",[prepareEmailAccountCommandSchema,revokeEmailAccountCommandSchema]);
export const trustedEmailAdapterAssertionSchema = z.object({adapterId:z.enum(["ENDVERA_LOCAL_AUTHENTICATED_R26","FUTURE_VERIFIED_EMAIL_ADAPTER"]),authenticityVerified:z.boolean(),externalTransportPerformed:z.literal(false)}).strict();

export const normalizedEmailInboundEventSchema = z.object({
  schemaVersion:z.literal(1),eventId:z.string().uuid(),workspaceId:z.string().min(1).max(160),accountId:z.string().min(1).max(160),providerMessageRef:emailRefSchema,threadRef:emailRefSchema.nullable(),previousCursorRef:emailRefSchema.nullable(),cursorRef:emailRefSchema,cursorContinuity:z.enum(["CURRENT","SYNC_REQUIRED"]),senderIdentityRef:emailRefSchema,recipientRefs:z.array(emailRefSchema).min(1).max(20),occurredAt:z.string().datetime(),subject:z.string().trim().min(1).max(998),normalizedBody:z.string().trim().min(1).max(10_000),projectId:z.string().min(1).max(160).nullable(),contactId:z.string().min(1).max(160).nullable(),selectedEvidenceIds:z.array(z.string().min(1).max(160)).max(20).default([]),verificationState:z.enum(["UNVERIFIED","HUMAN_CONFIRMED"]),externalTransportPerformed:z.literal(false),
}).strict();
export const prepareEmailDraftCommandSchema = z.object({schemaVersion:z.literal(1),action:z.literal("PREPARE_EMAIL_DRAFT"),commandId:z.string().uuid(),workspaceId:z.string().min(1).max(160),accountId:z.string().min(1).max(160),projectId:z.string().min(1).max(160),contactId:z.string().min(1).max(160),toRef:emailRefSchema,ccRefs:z.array(emailRefSchema).max(10).default([]),subject:z.string().trim().min(1).max(998),body:z.string().trim().min(1).max(10_000),threadRef:emailRefSchema.nullable(),selectedEvidenceIds:z.array(z.string().min(1).max(160)).max(20).default([]),expectedPolicyVersion:z.literal(EMAIL_POLICY_VERSION)}).strict();
export const approveEmailDraftCommandSchema = z.object({schemaVersion:z.literal(1),action:z.literal("APPROVE_EMAIL_DRAFT"),commandId:z.string().uuid(),workspaceId:z.string().min(1).max(160),draftId:z.string().min(1).max(160),expectedVersion:z.number().int().positive(),expectedPayloadHash:z.string().regex(/^[a-f0-9]{64}$/u)}).strict();

export const emailInboundResultSchema = z.object({schemaVersion:z.literal(1),eventId:z.string().uuid(),emailEventId:z.string().min(1),messageId:z.string().min(1),projectId:z.string().min(1).nullable(),contactId:z.string().min(1).nullable(),status:z.enum(["RESOLVED","CLARIFICATION_REQUIRED","REFUSED"]),reply:z.string().min(1).nullable(),canonicalEffectId:z.string().min(1).nullable(),evidenceLinkCount:z.number().int().nonnegative(),cursorStatus:z.enum(["CURRENT","SYNC_REQUIRED"]),replayed:z.boolean(),externalTransportPerformed:z.literal(false)}).strict();
export const preparedEmailDraftResultSchema = z.object({schemaVersion:z.literal(1),commandId:z.string().uuid(),draftId:z.string().min(1),workspaceId:z.string().min(1),projectId:z.string().min(1),contactId:z.string().min(1),toRef:emailRefSchema,ccRefs:z.array(emailRefSchema),subject:z.string().min(1),body:z.string().min(1),threadRef:emailRefSchema.nullable(),selectedEvidenceIds:z.array(z.string()),version:z.number().int().positive(),payloadHash:z.string().regex(/^[a-f0-9]{64}$/u),status:z.enum(["PREPARED_UNSENT","APPROVED_UNSENT"]),replayed:z.boolean(),externalTransportPerformed:z.literal(false)}).strict();
export const emailCockpitSchema = z.object({schemaVersion:z.literal(1),workspaceId:z.string().min(1),role:z.enum(["owner","admin","field_worker"]),accounts:z.array(z.object({id:z.string(),provider:emailProviderSchema,status:z.string(),version:z.number().int(),capabilities:z.array(z.string()),credentialStored:z.literal(false),externalTransportEnabled:z.literal(false)}).strict()),contacts:z.array(z.object({id:z.string(),projectId:z.string().nullable(),displayName:z.string(),emailRef:emailRefSchema}).strict()),events:z.array(z.object({id:z.string(),projectId:z.string().nullable(),contactId:z.string().nullable(),subject:z.string().nullable(),body:z.string().nullable(),status:z.string(),evidenceLinkCount:z.number().int(),occurredAt:z.string().datetime()}).strict()),drafts:z.array(z.object({id:z.string(),projectId:z.string(),contactId:z.string(),toRef:emailRefSchema.nullable(),subject:z.string().nullable(),body:z.string().nullable(),version:z.number().int(),payloadHash:z.string().nullable(),status:z.string(),createdAt:z.string().datetime()}).strict()),counts:z.object({accounts:z.number().int(),events:z.number().int(),preparedUnsent:z.number().int()}).strict(),providerObserved:z.literal(false),externalTransportEnabled:z.literal(false)}).strict().superRefine((v,ctx)=>{if(v.role==="field_worker"&&(v.accounts.length||v.contacts.length||v.events.length||v.drafts.length))ctx.addIssue({code:"custom",path:["role"],message:"FIELD_EMAIL_DETAILS_MUST_BE_EMPTY"});});

export type NormalizedEmailInboundEvent=z.infer<typeof normalizedEmailInboundEventSchema>;
export type EmailInboundResult=z.infer<typeof emailInboundResultSchema>;
export type PrepareEmailDraftCommand=z.infer<typeof prepareEmailDraftCommandSchema>;
export type ApproveEmailDraftCommand=z.infer<typeof approveEmailDraftCommandSchema>;
